// src/config/bookGenres.js
export const genreColors = {
  Torah: "#d4a373",
  Historical: "#8b8b8b",
  "Poetry/Wisdom": "#6b8e23",
  Prophets: "#8b0000",
  Gospels: "#1e90ff",
  Acts: "#32cd32",
  Epistles: "#9932cc",
  Revelation: "#ff4500",
};

export const bookToGenre = {
  GEN: "Torah",
  EXO: "Torah",
  LEV: "Torah",
  NUM: "Torah",
  DEU: "Torah",
  JOS: "Historical",
  JDG: "Historical",
  RUT: "Historical",
  "1SA": "Historical",
  "2SA": "Historical",
  "1KI": "Historical",
  "2KI": "Historical",
  "1CH": "Historical",
  "2CH": "Historical",
  EZR: "Historical",
  NEH: "Historical",
  EST: "Historical",
  JOB: "Poetry/Wisdom",
  PSA: "Poetry/Wisdom",
  PRO: "Poetry/Wisdom",
  ECC: "Poetry/Wisdom",
  SNG: "Poetry/Wisdom",
  ISA: "Prophets",
  JER: "Prophets",
  LAM: "Prophets",
  EZE: "Prophets",
  DAN: "Prophets",
  HOS: "Prophets",
  JOL: "Prophets",
  AMO: "Prophets",
  OBA: "Prophets",
  JON: "Prophets",
  MIC: "Prophets",
  NAM: "Prophets",
  HAB: "Prophets",
  SOP: "Prophets",
  HAG: "Prophets",
  ZEC: "Prophets",
  MAL: "Prophets",
  MAT: "Gospels",
  MRK: "Gospels",
  LUK: "Gospels",
  JHN: "Gospels",
  ACT: "Acts",
  ROM: "Epistles",
  "1CO": "Epistles",
  "2CO": "Epistles",
  GAL: "Epistles",
  EPH: "Epistles",
  PHP: "Epistles",
  COL: "Epistles",
  "1TH": "Epistles",
  "2TH": "Epistles",
  "1TI": "Epistles",
  "2TI": "Epistles",
  TIT: "Epistles",
  PHM: "Epistles",
  HEB: "Epistles",
  JAS: "Epistles",
  "1PE": "Epistles",
  "2PE": "Epistles",
  "1JN": "Epistles",
  "2JN": "Epistles",
  "3JN": "Epistles",
  JUD: "Epistles",
  REV: "Revelation",
};

export const getGenreColor = (bookCode) => {
  const genre = bookToGenre[bookCode];
  return genre ? genreColors[genre] : "#6c757d";
};
